-- Enable Row Level Security (RLS) is generally good practice, but for this demo/MVP 
-- we will start with public access to simplify the "migration" from local storage.
-- In a real production app, we would add strict Policies.

-- 1. Table: users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    password TEXT NOT NULL,
    must_change_password BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table: sites
CREATE TABLE IF NOT EXISTS sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    email TEXT, -- Added for reports
    status TEXT DEFAULT 'active',
    planned_hours INTEGER DEFAULT 0,
    geofence_lat DOUBLE PRECISION,
    geofence_lng DOUBLE PRECISION,
    geofence_radius_m INTEGER DEFAULT 150,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table: materials (tools)
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    serial_number TEXT,
    qr_code TEXT,
    status TEXT DEFAULT 'available',
    location_type TEXT DEFAULT 'warehouse', -- 'warehouse', 'site', 'repair'
    location_id BIGINT, -- Can be null (warehouse/repair) or site_id
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table: logs
CREATE TABLE IF NOT EXISTS logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT,
    user_id BIGINT REFERENCES users(id),
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table: company_info
CREATE TABLE IF NOT EXISTS company_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT
);

-- Seed Initial Data (Only if empty) because we want to start with something usable
INSERT INTO users (name, email, role, password)
SELECT 'Admin User', 'admin@company.com', 'admin', '123'
WHERE NOT EXISTS (SELECT 1 FROM users);

INSERT INTO company_info (name, address)
SELECT 'Antigravity Inc.', '123 Innovation Dr'
WHERE NOT EXISTS (SELECT 1 FROM company_info);

-- Disable RLS for now to allow anonymous read/write (since we handle auth in app logic for now)
-- WARNING: This relies on the anon key. In production, use Supabase Auth.
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sites DISABLE ROW LEVEL SECURITY;
ALTER TABLE materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE company_info DISABLE ROW LEVEL SECURITY;

-- 6. Table: tasks (Time Tracking)
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Alter Table: sites (Add planned_hours & Geofence)
-- ALTER TABLE sites ADD COLUMN planned_hours INTEGER DEFAULT 0;
-- ALTER TABLE sites ADD COLUMN geofence_lat DOUBLE PRECISION;
-- ALTER TABLE sites ADD COLUMN geofence_lng DOUBLE PRECISION;
-- ALTER TABLE sites ADD COLUMN geofence_radius_m INTEGER DEFAULT 150;

-- 7. Table: time_sessions (Time Tracking)
CREATE TABLE IF NOT EXISTS time_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    site_id BIGINT REFERENCES sites(id),
    task_id BIGINT REFERENCES tasks(id),
    punch_start_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    punch_end_at TIMESTAMP WITH TIME ZONE,
    gps_first_entry_at TIMESTAMP WITH TIME ZONE,
    gps_last_exit_at TIMESTAMP WITH TIME ZONE,
    
    -- Correction & Validation
    corrected_start_at TIMESTAMP WITH TIME ZONE,
    corrected_end_at TIMESTAMP WITH TIME ZONE,
    approved BOOLEAN DEFAULT FALSE,

    manual_entry BOOLEAN DEFAULT FALSE,
    gps_confidence BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- For the CREATE TABLE definition above (if re-running from scratch):
-- Update line 22 to: status TEXT DEFAULT 'active', planned_hours INTEGER DEFAULT 0,

-- Seed Tasks
INSERT INTO tasks (name)
SELECT 'Installation' WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE name = 'Installation');
INSERT INTO tasks (name)
SELECT 'Inspection' WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE name = 'Inspection');
INSERT INTO tasks (name)
SELECT 'Maintenance' WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE name = 'Maintenance');
INSERT INTO tasks (name)
SELECT 'Transport' WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE name = 'Transport');
INSERT INTO tasks (name)
SELECT 'Autre' WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE name = 'Autre');

-- Disable RLS for new tables
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE time_sessions DISABLE ROW LEVEL SECURITY;
