-- Enable Row Level Security (RLS) is generally good practice, but for this demo/MVP 
-- we will start with public access to simplify the "migration" from local storage.
-- In a real production app, we would add strict Policies.

-- 1. Table: users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
    password TEXT NOT NULL,
    must_change_password BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Table: sites
CREATE TABLE IF NOT EXISTS sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table: materials (tools)
CREATE TABLE IF NOT EXISTS materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    serial_number TEXT,
    qr_code TEXT,
    status TEXT DEFAULT 'available',
    location_type TEXT DEFAULT 'warehouse', -- 'warehouse', 'site', 'repair'
    location_id BIGINT, -- Can be null (warehouse/repair) or site_id
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table: logs
CREATE TABLE IF NOT EXISTS logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT,
    user_id BIGINT REFERENCES users(id),
    details TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table: company_info
CREATE TABLE IF NOT EXISTS company_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT
);

-- Seed Initial Data (Only if empty) because we want to start with something usable
INSERT INTO users (name, email, role, password)
SELECT 'Admin User', 'admin@company.com', 'admin', '123'
WHERE NOT EXISTS (SELECT 1 FROM users);

INSERT INTO company_info (name, address)
SELECT 'Antigravity Inc.', '123 Innovation Dr'
WHERE NOT EXISTS (SELECT 1 FROM company_info);

-- Disable RLS for now to allow anonymous read/write (since we handle auth in app logic for now)
-- WARNING: This relies on the anon key. In production, use Supabase Auth.
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sites DISABLE ROW LEVEL SECURITY;
ALTER TABLE materials DISABLE ROW LEVEL SECURITY;
ALTER TABLE logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE company_info DISABLE ROW LEVEL SECURITY;
