-- ==============================================================================
-- Migration: Add SaaS Multi-Tenant Layer
-- Description: Adds tables, companies relationships, and RLS policies 
-- without breaking the legacy authentication mechanism.
-- ==============================================================================

-- 1. Create SaaS Tables
CREATE TABLE IF NOT EXISTS public.companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.company_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    -- user_id is type TEXT to match the existing generic users IDs in your logic
    user_id TEXT NOT NULL, 
    role TEXT DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(company_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    token UUID DEFAULT gen_random_uuid() UNIQUE,
    email TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.company_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
    module_name TEXT NOT NULL,
    is_active BOOLEAN DEFAULT false,
    UNIQUE(company_id, module_name)
);

-- 2. Modify Existing Business Tables
-- (Addition of auth_user_id and company_id nullable fields)

ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_auth_user_id_key;
ALTER TABLE public.users ADD CONSTRAINT users_auth_user_id_key UNIQUE (auth_user_id);

ALTER TABLE public.sites ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.logs ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.time_sessions ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.project_tasks ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE;

-- 3. Backend Functions
-- Function to retrieve current security context company ID based on auth.uid()
CREATE OR REPLACE FUNCTION public.get_user_company_id()
RETURNS BIGINT
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT cu.company_id
  FROM public.company_users cu
  JOIN public.users u ON u.id::text = cu.user_id
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
$$;

-- Function to check if a specific module is active for user's company
CREATE OR REPLACE FUNCTION public.is_module_active(p_module_name TEXT)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT COALESCE(
    (SELECT is_active 
     FROM public.company_modules 
     WHERE company_id = public.get_user_company_id() AND module_name = p_module_name),
    false
  );
$$;

-- Example: Function to accept an invitation
CREATE OR REPLACE FUNCTION public.accept_invite(p_token UUID, p_user_id TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_company_id BIGINT;
BEGIN
  -- Mark the intent as accepted and map the user if valid
  SELECT company_id INTO v_company_id 
  FROM public.invites 
  WHERE token = p_token AND status = 'pending';

  IF v_company_id IS NOT NULL THEN
    -- Join company
    INSERT INTO public.company_users (company_id, user_id, role)
    VALUES (v_company_id, p_user_id, 'user')
    ON CONFLICT DO NOTHING;

    -- Update invite status
    UPDATE public.invites SET status = 'accepted' WHERE token = p_token;
    RETURN true;
  END IF;

  RETURN false;
END;
$$;

-- Function to create a company and automatically add the creator as admin
CREATE OR REPLACE FUNCTION public.create_company(p_name TEXT, p_user_id TEXT)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_company_id BIGINT;
BEGIN
  -- Insert into companies
  INSERT INTO public.companies (name) VALUES (p_name) RETURNING id INTO v_company_id;
  
  -- Insert mapping
  INSERT INTO public.company_users (company_id, user_id, role)
  VALUES (v_company_id, p_user_id, 'admin');
  
  -- Optionally add a default user in 'users' if passing a new ID to ensure referential integrity
  -- (Since users might be generated later, wait, 'users' must exist first if there is an FK? 
  -- company_users DOES NOT have an FK to users, it just joins on user_id::text)

  RETURN v_company_id;
END;
$$;

-- 4. Enable RLS on modified tables
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.company_modules ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tasks ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies Definition

-- companies
DROP POLICY IF EXISTS "Companies access" ON public.companies;
CREATE POLICY "Companies access" ON public.companies
  FOR ALL USING (
    id = public.get_user_company_id()
  );

-- We allow direct insert for newly registered users on companies so they can bootstrap
DROP POLICY IF EXISTS "Companies creation" ON public.companies;
CREATE POLICY "Companies creation" ON public.companies
  FOR INSERT WITH CHECK (
    auth.uid() IS NOT NULL
  );

-- company_users & company_modules
DROP POLICY IF EXISTS "company_users access" ON public.company_users;
CREATE POLICY "company_users access" ON public.company_users
  FOR ALL USING (
    company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "company_modules access" ON public.company_modules;
CREATE POLICY "company_modules access" ON public.company_modules
  FOR ALL USING (
    company_id = public.get_user_company_id()
  );

-- Generic Rule for Business Tables:
-- The rule ensures maximum backward compatibility (legacy): 
-- If company_id IS NULL -> Everyone has access (legacy data without SaaS constraints)
-- If company_id IS NOT NULL -> Only the users whose get_user_company_id() matches have access.

DROP POLICY IF EXISTS "Sites isolation" ON public.sites;
CREATE POLICY "Sites isolation" ON public.sites
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "Materials isolation" ON public.materials;
CREATE POLICY "Materials isolation" ON public.materials
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "Logs isolation" ON public.logs;
CREATE POLICY "Logs isolation" ON public.logs
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "Tasks isolation" ON public.tasks;
CREATE POLICY "Tasks isolation" ON public.tasks
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "Time sessions isolation" ON public.time_sessions;
CREATE POLICY "Time sessions isolation" ON public.time_sessions
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );

DROP POLICY IF EXISTS "Project tasks isolation" ON public.project_tasks;
CREATE POLICY "Project tasks isolation" ON public.project_tasks
  FOR ALL USING (
    company_id IS NULL OR company_id = public.get_user_company_id()
  );
