-- Create project_tasks table
CREATE TABLE IF NOT EXISTS public.project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT REFERENCES public.sites(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    planned_hours NUMERIC DEFAULT 0,
    completed_hours NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.project_tasks ENABLE ROW LEVEL SECURITY;

-- Policies (adjust as needed, currently open for auth users based on existing pattern)
CREATE POLICY "Enable read access for all users" ON public.project_tasks FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.project_tasks FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public.project_tasks FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public.project_tasks FOR DELETE USING (auth.role() = 'authenticated');
