-- 1. Table: weekly_timesheets
CREATE TABLE IF NOT EXISTS weekly_timesheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    week_start DATE,
    week_end DATE,
    total_hours NUMERIC(6,2), -- Added as requested
    leader_validated BOOLEAN DEFAULT FALSE,
    leader_validated_at TIMESTAMP,
    admin_validated BOOLEAN DEFAULT FALSE,
    admin_validated_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT now()
);

-- 2. Table: weekly_timesheet_entries
CREATE TABLE IF NOT EXISTS weekly_timesheet_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timesheet_id BIGINT REFERENCES weekly_timesheets(id) ON DELETE CASCADE,
    site_id BIGINT REFERENCES sites(id),
    section_id BIGINT REFERENCES project_tasks(id),
    hours NUMERIC(6,2),
    source TEXT CHECK (source IN ('punch','manual')), -- Keeping source for service compatibility
    created_at TIMESTAMP DEFAULT now()
);

-- 3. Indexes
CREATE INDEX IF NOT EXISTS idx_weekly_timesheets_user_id ON weekly_timesheets(user_id);
CREATE INDEX IF NOT EXISTS idx_weekly_timesheets_week_start ON weekly_timesheets(week_start);
CREATE INDEX IF NOT EXISTS idx_weekly_entries_timesheet_id ON weekly_timesheet_entries(timesheet_id);
